### ISSUE TITLE
How/where to get executable file for Dependent peptide search

### ISSUE THREAD

**Issue by Luq16** [jdrudolph/PluginDependentPeptides#1]
Hi,
I was try to do DP search. When trying to upload  file from Maxquant, there is a section that asks for "Executable" file under "generic" . Please which file am I supposed to upload here.

Thank you.

**Comment by jdrudolph** [comment]
Please read the `README` carefully. You need to install Python and perseuspy in order to use PluginDependentPeptides. Once installed, you have to select the path to your `python.exe` in the 'Executable' option. If you followed the instructions carefully, Perseus should be able to automatically detect your python installation and fill in the parameter automatically.

**Comment by Luq16** [comment]
Thank you. I get it to work now.
But I have another question. The values that appear in the  column
"Main"after uploading my allPeptides file into Persus are what? Thank you.

Best regards,
Luqman Awoniyi.

**Comment by jdrudolph** [comment]
These are the quantifications for all dependent peptides
