### ISSUE TITLE
explantation about the result in allPeptides.txt

### ISSUE THREAD

**Issue by ATPs** [jdrudolph/PluginDependentPeptides#3]
Hi, Jan. I followed the instruction to install this Plugin, but it did not work.  Anyway,  not a big problem. I am curious about the meaning of columns in allPeptides.txt file.

Below is one line I got. So it means, the DP (dependent peptide) almost have the same Mass? 
what does each of the name mean? so what is the final "dependent peptide" looks like? 
the "DP Ratio mod/base: 1150.877133" means that the DP is 1000 times more than the base sequence? What's the meaning of probabilities after the amino acids, like "L(0.063)I(0.063)"?

Hope to get some guidance from you.
Best.
Xiaolong

DP Mass Difference:	0.0003904
DP Time Difference:	-44.8766
DP Score:	74.949
DP PEP:	0.0085367
DP Positional Probability:	0.0625
DP Base Sequence:	LIDLTQFPAFVTPMGK
DP Probabilities:	L(0.063)I(0.063)D(0.063)L(0.063)T(0.063)Q(0.063)F(0.063)P(0.063)A(0.063)F(0.063)V(0.063)T(0.063)P(0.063)M(0.063)G(0.063)K(0.063)
DP AA:	nterm;L;I;D;T;Q;F;P;A;V;M;G;cterm;K
DP Base Scan Number:	12338
DP Mod Scan Number:	8444
DP Decoy:	
DP Proteins:	YLR044C
DP Cluster Index:	384
DP Cluster Mass:	1.21E-05
DP Cluster Mass SD:	0.002152731
DP Cluster Size Total:	288
DP Cluster Size Forward:	279
DP Cluster Size Reverse:	9
DP Modification:	Unmodified
DP Peptide Length Difference:	0
DP Ratio mod/base:	1150.877133

**Comment by ATPs** [comment]
I am trying to see the "mutated" amino acids from dependent peptides. You know, the protein database might be a little different from the strain used. For example, E. coli, different strains will have some "point" mutations for some amino acids. while the whole sequences are similar, some amino acids may be different. If I can find point mutations like serine to alanine, I can know the "preferred" amino acids.
Based on my understanding, the search of dependent peptides includes such possible "point mutations" for known peptides. How do I get such info? 
Thanks!

**Comment by jdrudolph** [comment]
We are currently working on the documentation for DP. Please post any further questions which are not related to the code of the plugin on the [Perseus google group](https://groups.google.com/forum/#!forum/perseus-list).
The DP mass difference is very small, so DP Modification says it's an 'Unmodified' version of the base peptide, which can happen due to the increased sensitivity of the DP search. The Ratio mod/base is not informative for unmodified peptides.
The location probabilities L(0.063) are calculated in a similar fashion to the PTM localization score in MaxQuant. In your example you can see poor localization, as expected for an unmodified peptide.
Amino acid substitutions can be identified by DP search and are denoted as AA->AA in the DP Modification column.

**Comment by ATPs** [comment]
Thank you a lot!
